"""Build standalone profiles using only reviewed repository inputs (no downloads)."""
import argparse
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
VERSION = '5.1.0-rc.1'
LOCAL = {
    'user-proxy.list': 'PROXY',
    'user-direct.list': 'DIRECT',
    'china-core.list': 'DIRECT',
}
BASE_URL = 'https://raw.githubusercontent.com/menghuaban520/cloudflaresub/main/configs/rules/'
OPTIONAL = {
    'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/AdvertisingLite/AdvertisingLite_Domain.list',
    'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/AdvertisingLite/AdvertisingLite.list',
    'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/ChinaMax/ChinaMax_Domain.list',
}


def read_rules(text, policy):
    rules = []
    for number, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith(('#', ';')):
            continue
        parts = line.split(',')
        if len(parts) != 2 or parts[0] not in ('DOMAIN', 'DOMAIN-SUFFIX'):
            raise ValueError(f'Unsupported local rule at line {number}: {line}')
        domain = parts[1]
        labels = domain.split('.')
        if len(domain) > 253 or any(not re.fullmatch(r'[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?', label) for label in labels):
            raise ValueError(f'Invalid ASCII domain at line {number}: {domain}')
        rules.append(f'{line},{policy}')
    return rules


def render(source, lists, ads=True):
    output = [f'# Shadowrocket Standalone {VERSION}',
              '# Generated by scripts/build_shadowrocket.py; edit repository sources.',
              '# 无远程规则下载 / 无自动更新；DNS 与节点仍需联网。',
              '# 候选版：尚未完成 iPhone 实机验收；跟随首页手动选择的节点。']
    section = None
    seen = set()
    expanded = set()
    for raw in source.splitlines():
        line = raw.strip()
        if not line or line.startswith(('#', ';')):
            continue
        if line.startswith('['):
            section = line
            if section not in ('[General]', '[Proxy]', '[Proxy Group]', '[Rule]', '[Host]'):
                raise ValueError(f'Unexpected section: {section}')
            output.extend(['', line])
            continue
        if section in ('[Proxy]', '[Proxy Group]'):
            raise ValueError('Public profiles must not contain nodes or groups')
        if section == '[General]' and line.split('=', 1)[0].strip() == 'update-url':
            continue
        candidates = [line]
        if section == '[Rule]' and line.startswith(('RULE-SET,', 'DOMAIN-SET,')):
            parts = line.split(',')
            url, policy = parts[1:3]
            name = url.removeprefix(BASE_URL)
            if url.startswith(BASE_URL) and name in LOCAL:
                if policy != LOCAL[name]:
                    raise ValueError(f'Unexpected policy for {name}')
                candidates = read_rules(lists[name], policy)
                expanded.add(name)
            elif url in OPTIONAL:
                continue
            else:
                raise ValueError(f'Unreviewed remote dependency: {url}')
        for candidate in candidates:
            if section == '[Rule]':
                if not ads and candidate.split(',')[-1] == 'REJECT':
                    continue
                if candidate in seen:
                    continue
                seen.add(candidate)
            output.append(candidate)
    if expanded != set(LOCAL):
        raise ValueError('Missing local override/core list reference')
    return '\n'.join(output) + '\n'


def artifacts(root=ROOT):
    source_path = root / 'configs/shadowrocket-pro.conf'
    inputs = [source_path] + [root / 'configs/rules' / name for name in LOCAL]
    lists = {name: (root / 'configs/rules' / name).read_text() for name in LOCAL}
    result = {}
    for name, ads in [('shadowrocket-standalone.conf', True), ('shadowrocket-standalone-noads.conf', False)]:
        content = render(source_path.read_text(), lists, ads).encode()
        result[f'configs/{name}'] = content
        result[f'public/{name}'] = content
    manifest = {
        'version': VERSION,
        'status': 'release-candidate; iOS validation pending',
        'inputs': {str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest() for p in inputs},
        'outputs': {name: hashlib.sha256(data).hexdigest() for name, data in result.items()},
    }
    result['configs/shadowrocket-build.json'] = (json.dumps(manifest, indent=2) + '\n').encode()
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if committed output is stale')
    args = parser.parse_args()
    generated = artifacts()  # Validate every input before writing anything.
    stale = []
    for name, content in generated.items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_bytes() != content:
                stale.append(name)
        else:
            path.write_bytes(content)
    if stale:
        parser.exit(1, 'Stale output; run python3 scripts/build_shadowrocket.py:\n' + '\n'.join(stale) + '\n')
    print(f'{VERSION}: {len(generated)} artifacts ' + ('verified' if args.check else 'built'))


if __name__ == '__main__':
    main()
